matrix:
  include:
    - os: linux
      dist: trusty
      # TravisCI doesn't support testing bash versions so
      # just pretend we are testing a python project
      language: python
      python: 3.5
      sudo: required
    - os: osx
      # FIXME: Workaround lack of python support
      # on TravisCI osx builders.
      # https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      sudo: required
install:
  - tests/travisci_install.sh
script:
  - tests/run.sh
